#!/bin/bash

##SetupLive
#NKSOSのライブ環境を正しくするために使われます。
function live_check(){
    if dpkg -l | grep -q "ubiquity"; then
    echo "Ubiquity is installed."
    echo "ライブ環境です。"
    #グローバルテーマを反映
    plasma-apply-lookandfeel -a com.nksteam.nksos
    #Plasmaテーマの反映
    plasma-apply-desktoptheme Materia-Color
    #壁紙を反映
    plasma-apply-wallpaperimage /usr/share/wallpapers/nkswallpaper-old/contents/screenshot.png
    exit
else
    echo "Ubiquityがありません。"
    echo "ライブ環境では、ありません"
    echo "初回起動かどうかチェックします"
    first_boot_check
fi
}

function first_boot_check (){
    marker_file = "${home}/.firstboot";
    if [ -f "$marker_file" ]; then
        echo "Not the first boot."
        echo "初回起動では、ありません。"
        echo "実行しません。"
        exit
    else
        echo "First boot."
        echo "設定します"
        #グローバルテーマを反映
        plasma-apply-lookandfeel -a com.nksteam.nksos
        #Plasmaテーマの反映
        plasma-apply-desktoptheme Materia-Color
        #壁紙を反映
        plasma-apply-wallpaperimage /usr/share/wallpapers/nkswallpaper-old/contents/screenshot.png

    fi
}